# Generated by Django 5.2.7 on 2025-10-04 06:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_entry_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='date',
        ),
        migrations.AddField(
            model_name='entry',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='entry',
            name='glucose',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='weight',
            field=models.FloatField(),
        ),
    ]
