# Generated by Django 5.2.7 on 2025-10-04 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_medicine_premiumsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='premiumsubscription',
            old_name='started_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='premiumsubscription',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='premiumsubscription',
            name='plan',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='schedule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='premiumsubscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
