# Generated by Django 5.2.7 on 2025-10-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_rename_started_at_premiumsubscription_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='time1',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='time2',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='time3',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='time4',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
