# Generated by Django 5.2.7 on 2025-10-04 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_rename_time1_medicine_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='user',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='MedicineTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='diary.medicine')),
            ],
        ),
        migrations.DeleteModel(
            name='PremiumSubscription',
        ),
    ]
