# Generated by Django 5.2.7 on 2025-10-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_remove_medicine_end_time_remove_medicine_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='dose',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicinetime',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
