# Generated by Django 5.2.7 on 2025-10-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_alter_medicine_dose_alter_medicine_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
