# Generated by Django 5.2.7 on 2025-10-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_alter_userprofile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinetime',
            name='last_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
